// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package net.exoad.linkvault

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object AppApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** What an external Android intent wants the hub to do. */
enum class IntentKind(val raw: Int) {
  /** A URL was shared/selected — save it as a link. */
  SAVE_LINK(0),
  /** Start a new note (empty or seeded with [IncomingIntent.text]). */
  NEW_NOTE(1),
  /** Generic shared text with no obvious URL — let a module decide. */
  SHARE_TEXT(2);

  companion object {
    fun ofRaw(raw: Int): IntentKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class LlmBackend(val raw: Int) {
  CPU(0),
  GPU(1);

  companion object {
    fun ofRaw(raw: Int): LlmBackend? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class LlmHistoryRole(val raw: Int) {
  USER(0),
  ASSISTANT(1),
  TOOL(2);

  companion object {
    fun ofRaw(raw: Int): LlmHistoryRole? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * A normalized external intent delivered from Kotlin to Flutter.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class IncomingIntent (
  val kind: IntentKind,
  /** Shared/selected text or URL, if any. */
  val text: String? = null,
  /** Optional hub module id hint (e.g. from a launcher shortcut). */
  val targetModuleId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IncomingIntent {
      val kind = pigeonVar_list[0] as IntentKind
      val text = pigeonVar_list[1] as String?
      val targetModuleId = pigeonVar_list[2] as String?
      return IncomingIntent(kind, text, targetModuleId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      text,
      targetModuleId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as IncomingIntent
    return AppApiPigeonUtils.deepEquals(this.kind, other.kind) && AppApiPigeonUtils.deepEquals(this.text, other.text) && AppApiPigeonUtils.deepEquals(this.targetModuleId, other.targetModuleId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AppApiPigeonUtils.deepHash(this.kind)
    result = 31 * result + AppApiPigeonUtils.deepHash(this.text)
    result = 31 * result + AppApiPigeonUtils.deepHash(this.targetModuleId)
    return result
  }
}

/**
 * Result of comparing the installed app signature to a downloaded APK.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ApkSigningResult (
  val compatible: Boolean,
  val installedCertSha256: String? = null,
  val apkCertSha256: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ApkSigningResult {
      val compatible = pigeonVar_list[0] as Boolean
      val installedCertSha256 = pigeonVar_list[1] as String?
      val apkCertSha256 = pigeonVar_list[2] as String?
      return ApkSigningResult(compatible, installedCertSha256, apkCertSha256)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      compatible,
      installedCertSha256,
      apkCertSha256,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ApkSigningResult
    return AppApiPigeonUtils.deepEquals(this.compatible, other.compatible) && AppApiPigeonUtils.deepEquals(this.installedCertSha256, other.installedCertSha256) && AppApiPigeonUtils.deepEquals(this.apkCertSha256, other.apkCertSha256)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AppApiPigeonUtils.deepHash(this.compatible)
    result = 31 * result + AppApiPigeonUtils.deepHash(this.installedCertSha256)
    result = 31 * result + AppApiPigeonUtils.deepHash(this.apkCertSha256)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LlmHistoryMessage (
  val role: LlmHistoryRole,
  val content: String,
  val toolName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LlmHistoryMessage {
      val role = pigeonVar_list[0] as LlmHistoryRole
      val content = pigeonVar_list[1] as String
      val toolName = pigeonVar_list[2] as String?
      return LlmHistoryMessage(role, content, toolName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      role,
      content,
      toolName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LlmHistoryMessage
    return AppApiPigeonUtils.deepEquals(this.role, other.role) && AppApiPigeonUtils.deepEquals(this.content, other.content) && AppApiPigeonUtils.deepEquals(this.toolName, other.toolName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AppApiPigeonUtils.deepHash(this.role)
    result = 31 * result + AppApiPigeonUtils.deepHash(this.content)
    result = 31 * result + AppApiPigeonUtils.deepHash(this.toolName)
    return result
  }
}

/**
 * Sampling and context limits (applied when loading or updating session).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LlmGenerationConfig (
  val temperature: Double,
  val topK: Long,
  val topP: Double,
  val maxOutputTokens: Long,
  val contextTokenLimit: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LlmGenerationConfig {
      val temperature = pigeonVar_list[0] as Double
      val topK = pigeonVar_list[1] as Long
      val topP = pigeonVar_list[2] as Double
      val maxOutputTokens = pigeonVar_list[3] as Long
      val contextTokenLimit = pigeonVar_list[4] as Long
      return LlmGenerationConfig(temperature, topK, topP, maxOutputTokens, contextTokenLimit)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      temperature,
      topK,
      topP,
      maxOutputTokens,
      contextTokenLimit,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LlmGenerationConfig
    return AppApiPigeonUtils.deepEquals(this.temperature, other.temperature) && AppApiPigeonUtils.deepEquals(this.topK, other.topK) && AppApiPigeonUtils.deepEquals(this.topP, other.topP) && AppApiPigeonUtils.deepEquals(this.maxOutputTokens, other.maxOutputTokens) && AppApiPigeonUtils.deepEquals(this.contextTokenLimit, other.contextTokenLimit)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AppApiPigeonUtils.deepHash(this.temperature)
    result = 31 * result + AppApiPigeonUtils.deepHash(this.topK)
    result = 31 * result + AppApiPigeonUtils.deepHash(this.topP)
    result = 31 * result + AppApiPigeonUtils.deepHash(this.maxOutputTokens)
    result = 31 * result + AppApiPigeonUtils.deepHash(this.contextTokenLimit)
    return result
  }
}

/**
 * Estimated context fill for the active native session.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LlmContextStats (
  val usedTokens: Long,
  val maxTokens: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LlmContextStats {
      val usedTokens = pigeonVar_list[0] as Long
      val maxTokens = pigeonVar_list[1] as Long
      return LlmContextStats(usedTokens, maxTokens)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      usedTokens,
      maxTokens,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LlmContextStats
    return AppApiPigeonUtils.deepEquals(this.usedTokens, other.usedTokens) && AppApiPigeonUtils.deepEquals(this.maxTokens, other.maxTokens)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AppApiPigeonUtils.deepHash(this.usedTokens)
    result = 31 * result + AppApiPigeonUtils.deepHash(this.maxTokens)
    return result
  }
}
private open class AppApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          IntentKind.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LlmBackend.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LlmHistoryRole.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IncomingIntent.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApkSigningResult.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LlmHistoryMessage.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LlmGenerationConfig.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LlmContextStats.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is IntentKind -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is LlmBackend -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is LlmHistoryRole -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is IncomingIntent -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ApkSigningResult -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is LlmHistoryMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is LlmGenerationConfig -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is LlmContextStats -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Android package-install + signing operations (implemented in Kotlin).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface InstallHostApi {
  /** Whether the user allows this app to install packages (Android 8+). */
  fun canInstallPackages(): Boolean
  /** Opens the system "install unknown apps" settings screen for this app. */
  fun openInstallPermissionSettings()
  /** Compares the installed app certificate with the APK at [path]. */
  fun checkApkSigning(path: String): ApkSigningResult
  /**
   * Launches the system package installer for the APK at [path].
   *
   * Throws a `SIGNING_MISMATCH` coded error if the APK was signed with a
   * different key than the installed app.
   */
  fun installApk(path: String)

  companion object {
    /** The codec used by InstallHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      AppApiPigeonCodec()
    }
    /** Sets up an instance of `InstallHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: InstallHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.InstallHostApi.canInstallPackages$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.canInstallPackages())
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.InstallHostApi.openInstallPermissionSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openInstallPermissionSettings()
              listOf(null)
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.InstallHostApi.checkApkSigning$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.checkApkSigning(pathArg))
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.InstallHostApi.installApk$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.installApk(pathArg)
              listOf(null)
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native shell hooks (splash handoff, window polish).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface UiHostApi {
  /** Called after the first Flutter frame so Android can dismiss the splash. */
  fun notifyUiReady()

  companion object {
    /** The codec used by UiHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      AppApiPigeonCodec()
    }
    /** Sets up an instance of `UiHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: UiHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.UiHostApi.notifyUiReady$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.notifyUiReady()
              listOf(null)
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * External intent entry point that Flutter pulls from on startup (Kotlin).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface IntentHostApi {
  /**
   * Returns the intent that launched the app (share/shortcut), if any.
   *
   * Consumed once: a second call returns null. Avoids the cold-start race
   * where the host could fire before Flutter registers [FlutterIntentApi].
   */
  fun getInitialIntent(): IncomingIntent?

  companion object {
    /** The codec used by IntentHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      AppApiPigeonCodec()
    }
    /** Sets up an instance of `IntentHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: IntentHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.IntentHostApi.getInitialIntent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getInitialIntent())
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * External intents pushed from Kotlin into Flutter while running (warm start).
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class FlutterIntentApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by FlutterIntentApi. */
    val codec: MessageCodec<Any?> by lazy {
      AppApiPigeonCodec()
    }
  }
  fun onIntent(intentArg: IncomingIntent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.linkvault.FlutterIntentApi.onIntent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(intentArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(AppApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
/**
 * Native Gemma inference (download, load, stream) on Android.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface LlmHostApi {
  fun isModelInstalled(fileName: String): Boolean
  /** Downloads to app files dir. Progress via [FlutterLlmApi.onDownloadProgress]. */
  fun startModelDownload(url: String, fileName: String, bearerToken: String?)
  fun cancelModelDownload()
  fun uninstallModel(fileName: String)
  /** Loads weights and prepares a session. Heavy; call off UI thread (native does). */
  fun loadModel(fileName: String, backend: LlmBackend, maxTokens: Long, callback: (Result<Unit>) -> Unit)
  fun unloadModel()
  fun resetConversation()
  /** Replays Drift history into the native session (no generation). */
  fun replayHistory(messages: List<LlmHistoryMessage>)
  /** Queues the user turn (call [startGeneration] after). */
  fun sendUserMessage(text: String)
  /** After a tool call, send result and call [startGeneration] again. */
  fun sendToolResult(toolName: String, resultJson: String)
  /** Streams tokens via [FlutterLlmApi.onToken] until done or tool call. */
  fun startGeneration()
  fun stopGeneration()
  /** `Using GPU`, `Using CPU`, or null if unloaded. */
  fun getActiveBackendLabel(): String?
  /** Updates sampler settings; recreates the native session with the same history. */
  fun applyGenerationConfig(config: LlmGenerationConfig)
  /** Rough token estimate for the loaded session (history + pending). */
  fun getContextStats(): LlmContextStats

  companion object {
    /** The codec used by LlmHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      AppApiPigeonCodec()
    }
    /** Sets up an instance of `LlmHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LlmHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.LlmHostApi.isModelInstalled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fileNameArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.isModelInstalled(fileNameArg))
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.LlmHostApi.startModelDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val fileNameArg = args[1] as String
            val bearerTokenArg = args[2] as String?
            val wrapped: List<Any?> = try {
              api.startModelDownload(urlArg, fileNameArg, bearerTokenArg)
              listOf(null)
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.LlmHostApi.cancelModelDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancelModelDownload()
              listOf(null)
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.LlmHostApi.uninstallModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fileNameArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.uninstallModel(fileNameArg)
              listOf(null)
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.LlmHostApi.loadModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fileNameArg = args[0] as String
            val backendArg = args[1] as LlmBackend
            val maxTokensArg = args[2] as Long
            api.loadModel(fileNameArg, backendArg, maxTokensArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AppApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(AppApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.LlmHostApi.unloadModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.unloadModel()
              listOf(null)
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.LlmHostApi.resetConversation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.resetConversation()
              listOf(null)
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.LlmHostApi.replayHistory$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messagesArg = args[0] as List<LlmHistoryMessage>
            val wrapped: List<Any?> = try {
              api.replayHistory(messagesArg)
              listOf(null)
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.LlmHostApi.sendUserMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.sendUserMessage(textArg)
              listOf(null)
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.LlmHostApi.sendToolResult$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val toolNameArg = args[0] as String
            val resultJsonArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.sendToolResult(toolNameArg, resultJsonArg)
              listOf(null)
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.LlmHostApi.startGeneration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startGeneration()
              listOf(null)
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.LlmHostApi.stopGeneration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopGeneration()
              listOf(null)
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.LlmHostApi.getActiveBackendLabel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getActiveBackendLabel())
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.LlmHostApi.applyGenerationConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as LlmGenerationConfig
            val wrapped: List<Any?> = try {
              api.applyGenerationConfig(configArg)
              listOf(null)
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.linkvault.LlmHostApi.getContextStats$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getContextStats())
            } catch (exception: Throwable) {
              AppApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Streaming and download events from Kotlin to Dart.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class FlutterLlmApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by FlutterLlmApi. */
    val codec: MessageCodec<Any?> by lazy {
      AppApiPigeonCodec()
    }
  }
  fun onDownloadProgress(percentArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.linkvault.FlutterLlmApi.onDownloadProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(percentArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(AppApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onToken(tokenArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.linkvault.FlutterLlmApi.onToken$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(tokenArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(AppApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onGenerationComplete(fullTextArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.linkvault.FlutterLlmApi.onGenerationComplete$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(fullTextArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(AppApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onFunctionCall(nameArg: String, argsJsonArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.linkvault.FlutterLlmApi.onFunctionCall$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(nameArg, argsJsonArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(AppApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onLlmError(codeArg: String, messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.linkvault.FlutterLlmApi.onLlmError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(codeArg, messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(AppApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
